### ISSUE TITLE
S2LP packet sniffer does not compile in Standard configuration

### ISSUE THREAD

**Issue by tobbad** [STMicroelectronics/x-cube-subg2#11]
**Describe the set-up**
 * 2 x Nucleo F401.
 * 2 x Radio shield S2868A2
 * Setup according to Document in the Project:
![image](https://github.com/user-attachments/assets/28492730-2d2c-4e5a-8453-6d61b81627a5)
![image](https://github.com/user-attachments/assets/6e8c207c-75b3-4f9a-bbe0-af9a1275790a)

**Describe the bug**
Compiling does not work out of the box. The are several places where DEBUG is defined. I protected these defines with a 
#ifndef DEBUG
#define DEBUG 0
#endif
clause. However when I compile the code I get following errors
[sniffer_problem.txt](https://github.com/user-attachments/files/16578773/sniffer_problem.txt)
The stlink of the Boards is in the latest version. I did a small HW modification to output the radio led to PC7/CN2 pin2. I am using following STM32CubeIDE 
![image](https://github.com/user-attachments/assets/4c68d4bb-3206-477b-a4fc-655e78595508)

**Comment by mgrella** [comment]
Hello @tobbad ,

sorry for late reply (holiday period). Tomorrow I'll try to reproduce your issue.

Some misc preliminary question:
- have you tried to compile the sniffer application included in the repo?
- if you reconfigured the project, could you please share your ioc file? (did you use CubeMX? which version?)

thank you and best regards,
Marco

**Comment by tobbad** [comment]
Using the default sniffer app only gave the error 
![image](https://github.com/user-attachments/assets/ae450bbd-2d65-4a8f-bfec-9e690a562207)
but it compiled ok.

Thanks

**Comment by mgrella** [comment]
Hello @tobbad,

since I see, in you error log, the "--specs=nano.specs" directive, I guess that you need to change the runtime library to "Standard". This is required for application based on Contiki-NG, please check the STM32CubeMX Getting started guide of X-CUBE-SUBG2 (page 35. "Known Limitations and workarounds section", first entry) or the Release Note in "Known Limitations" section:

> When using STM32CubeMX SUBG2 pack, the Contiki-NG based projects for STM32CubeIDE must use “Standard C” library instead of the default “Reduced C” (Properties, C/C++ Build, Settings, MCU Settings, Runtime library => Standard C).

Please let me know if this solves your issue.

For the "DEBUG" redefinition (and other warnings with some source cause), our policy is not to change third party Middlewares (like Contiki-NG) code, if possible, and the command line "DEBUG" is defined by the IDE for the DEBUG (default) configuration.

The last warning ("...LOAD segment with RWX permissions") is raised in recent STM32CubeIDE version, but should be already solved if you use last STM32CubeMX tool to reconfigure the project (I do not see it any more with STM32CubeMX 6.12 and STM32CubeIDE 1.16). Which tool did you use to regenerate the project?

BR,
Marco

**Comment by tobbad** [comment]
Using the default sniffer app only gave the error 
![image](https://github.com/user-attachments/assets/ae450bbd-2d65-4a8f-bfec-9e690a562207)
but it compiled ok.

Thanks

**Comment by tobbad** [comment]
Hello

Is there a way to obtain the Stm orignal spirit1 Repo. On the internet i can not find it amywhere but I still own two shields.

Regards
Tobias Badertscher

28.08.2024 12:02:53 Marco Grella ***@***.***>:
