### ISSUE TITLE
S2-LP RSSI_TH "0.5 dB steps" comment wrong?

### ISSUE THREAD

**Issue by pieterconradie** [STMicroelectronics/x-cube-subg2#6]
Hi there!

See here:
https://github.com/STMicroelectronics/x-cube-subg2/blob/main/Drivers/BSP/Components/S2LP/S2LP_Library/inc/S2LP_Regs.h#L364

The comment states that the RSSI_TH signal detect threshold is in 0.5 dB steps but in the S2-LP datasheet (page 68) it is stated that it is in 1 dB steps.

Best regards,
Pieter

**Comment by mgrella** [comment]
Hello @pieterconradie ,
thank you for spotting out and reporting this discrepancy. I am in contact with S2-LP DK team in order to confirm which statement is correct.

Best regards,
Marco

**Comment by mgrella** [comment]
Hello @pieterconradie ,

so I confirm that the datasheet is correct, the threshold is in 1dB steps. Moreover, the default value is actually 0x28 but it corresponds to -106 dB, not -120 dB as reported in the comment. I am going to update the file reflecting these fixes. Please note that, at least for the moment, no further releases of the S2-LP DK where the driver is derived from are planned, so that package available on st.com will not be updated.

Thank you and best regards,
Marco

**Comment by pieterconradie** [comment]
Hi @mgrella,

Thanks for looking into it and confirming that the datasheet is correct :)

Best regards,
Pieter
