### ISSUE TITLE
S2LPWhitening and S2LPFec are not implemented

### ISSUE THREAD

**Issue by umeda-skyley** [STMicroelectronics/x-cube-subg2#9]
S2LPPktBasicWhitening(S_ENABLE);
S2LPPktStackWhitening(S_ENABLE);
S2LPPktBasicFec(S_ENABLE);
S2LPPktStackFec(S_ENABLE);

these code causes:

Error[Li005]: no definition for "S2LPWhitening"
Error[Li005]: no definition for "S2LPFec"

**Comment by mgrella** [comment]
Hello @umeda-skyley ,

sorry for late reply.
Yes, I do confirm that S2LPWhitening and S2LPFec are not implemented.
I think that S2LPPacketHandlerWhitening() and S2LPPacketHandlerFec() should be respectively used, instead (I am cross checking with S2-LP Driver team).

BR,
Marco

**Comment by mgrella** [comment]
Hello @umeda-skyley ,

agreed, the correct fix is to change those 4 macros like follows.

In S2LP_PktStack.h:
#define S2LPPktStackWhitening(xNewState)    S2LPPacketHandlerWhitening(xNewState)
#define S2LPPktStackFec(xNewState)               S2LPPacketHandlerFec(xNewState)

In S2LP_PktBasic.h:
#define S2LPPktBasicWhitening(xNewState)    S2LPPacketHandlerWhitening(xNewState)
#define S2LPPktBasicFec(xNewState)               S2LPPacketHandlerFec(xNewState)

Just let me know if you prefer to open a Pull request for this, otherwise I can simply patch the files.

Best regards and thank you very much again for discovering and reporting the issue,
Marco

**Comment by umeda-skyley** [comment]
Hello Marco,

Thank you for the confirmation.
I agree with your solution.
so could you patch those files please?
Then I'll close my fork repository soon.

**Comment by mgrella** [comment]
Done,
BR,
Marco
